name: ie7615-captioning
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pillow
  - tqdm
  - pyyaml
  - jupyter
  - ipykernel
  - ipywidgets
  - pip:
      - torch
      - transformers
      - tokenizers
      - huggingface-hub
      - peft
      - accelerate
      - datasets
      - nltk
      - rouge-score
      - flask
